#
# Makefile for MELFAS MIP4 Touchscreen driver
#
ccflags-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438) += -DMIP_USE_DEVICETREE
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438)	+= mip4.o mip4_debug.o mip4_fw_mms438.o mip4_sec.o
